Map<String, String> en = {
  "المستودع": "Store",
  "الاجمالي": "Total",
  "الايرادات": "Revenues",
  "المصروف": "Expense",
  "الرواتب المستحقة": "Salaries owed",
  "الموظفين": "Employees",
  "موظف": "Employee",
  "اداري": "Administrative",
  "استاذ": "Teacher",
  "موظف مكتبي": "Office Employee",
  "سائق": "Driver",
  "الطلاب": "Students",
  "طالب": "Student",
  "ذكر": "Male",
  "انثى": "Female",
  "ذوي الهمم": "People of Determination",
  "دوام الموظفين": "Employee Attendance",
  "المدفوع": "Paid",
  "المستحق": "Due",
  "اولياء الامور": "Parents",
  "أولياء الامور": "Parents",
  "لوحة التحكم": "Dashboard",
  "الاسم الكامل": "Full Name",
  "العنوان": "Address",
  "الجنسية": "Nationality",
  "العمر": "Age",
  "العمل": "Job",
  "تاريخ البداية": "Start Date",
  "رقم الام": "Mother's Number",
  "رقم الطوارئ": "Emergency Number",
  "سجل الاحداث": "Event Log",
  "استرجاع": "Restore",
  "عرض": "Show",
  "سجل الأحداث": "Event Log",
  "الخيارات": "Options",
  "تعديل": "Edit",
  "حذف": "Delete",
  "اسم الطالب": "Student Name",
  "رقم الطالب": "Student Number",
  "الجنس": "Gender",
  "التولد": "Date of Birth",
  "الصف": "Grade",
  "الشعبة": "Class",
  "الحافلة": "Bus",
  "ولي الأمر": "Guardian",
  "علامات الطالب": "Student Grades",
  "المعدل": "Average",
  "الصفوف": "Grades",
  "يرجى إختيار احد الصفوف لمشاهدة تفاصيله":
      "Please Select a Grade to View Its Details",
  "الدوام": "Attendance",
  "لايوجد طلاب": "No Students",
  "تسجيل دخول الموظف": "Employee Login",
  "عرض تفاصيل الموظف": "View Employee Details",
  "هذا الجهاز لا يحتوي قارئ NFC": "This Device Does Not Have an NFC Reader",
  "الامتحانات": "Exams",
  "المقرر": "Course",
  "الأستاذ": "Teacher",
  "التاريخ": "Date",
  "علامة النجاح": "Passing Mark",
  "نسبة النجاح": "Pass Rate",
  "صورة": "Image",
  "اضافة علامات": "Add Grades",
  "الرواتب": "Salaries",
  "ادارة رواتب الموظفين": "Manage Employee Salaries",
  "اختر الشهر": "Select Month",
  "الراتب المستحق": "Due Salary",
  "الراتب الكلي": "Total Salary",
  "العمليات": "Operations",
  "الراتب المستلم": "Received Salary",
  "الحافلات": "Buses",
  "رقم الحافلة": "Bus Number",
  "اسم الحافلة": "Bus Name",
  "عدد الطلاب": "Number of Students",
  "عدد الموظفين": "Number of Employees",
  "الرسوم الدراسية": "Students Fees",
  "الدفعات القادمة": "Upcoming Payments",
  "الدفعات المستلمة": "Received Payments",
  "الدفعات المتأخرة": "Late Payments",
  "الاولاد": "Children",
  "المستلم": "Recipient",
  "المبلغ الكامل": "Full Amount",
  "الحالة": "Status",
  "اضافة دفعة": "Add Payment",
  "الأحداث": "Events",
  "الرمز التسلسلي": "Serial Number",
  "المستهدف": "Target",
  "اللون": "Color",
  "المصاريف": "Expenses",
  "المبلغ": "Amount",
  "اسم الموظف": "Employee Name",
  "الوصف": "Description",
  "كامل الوصف": "Full Description",
  "عدد الفواتير المدخلة": "Number of Invoices Entered",
  "الصور": "Images",
  "عرض التفاصيل": "View Details",
  "عرض الصور": "View Images",
  "ادارة المنصة": "Management",
  "سجلات الموظفين": "Employee Records",
  "كلمة السر": "Password",
  "الدور": "Role",
  "رقم الموبايل": "Mobile Number",
  "الوظيفة": "Job",
  "العقد": "Contract",
  "الرمز التسلسلي المتأثر": "Affected Serial Number",
  "التصنيف المتأثر": "Affected Category",
  "ارجاع": "Return",
  "سجلات الحذف": "Deletion Records",
  "الارشفة وحذف البيانات": "Archiving and Deleting Data",
  "السنة المختارة": "Selected Year",
  "ارشفة البيانات الحالية": "Archive Current Data",
  "تصفير البيانات الحالية": "Reset Current Data",
  "تقوم هذه الواجهة بعرض الامور الاساسية في المنصة وهي المستخدمين وامكانية اضافة او تعديل او حذف كما تعرض السجلات الممطلوب حذفها للموافقة عليها او استرجاعها كما يمكن ارشفة بيانات السنة الحالية او حذف البيانات او العودة الى نسخة سابقة":
      "This interface displays the basic aspects of the platform, including users with the ability to add, edit, or delete. It also shows records that need to be deleted for approval or restoration, and allows archiving current year's data, deleting data, or reverting to a previous version.",
  "يمكنك من اضافة مستخدم جديد": "Allows you to add a new user",
  "تعرض معلومات الحافلات مع امكانية اضافة حافلة جديدة او اضافة مصروف الى حافلة موجودة سابقا":
      "Displays bus information with the ability to add a new bus or add an expense to an existing bus",
  "تعرض هذه الواجهة كل المعلومات الاساسية عن حالة المدرسة والتي هي مجموع المصاريف مجموع الدفعات الواردة اجمالي الربح السنوي و الرواتب المستحقة لهذا الشهر كما ايضا تظهر تفصيل اعداد الطلاب وتفصيل اعداد الموظفين بالاضافة لمعرفة اوقات دوام الموظفين والرواتب المستحقة لهم لكل شهر":
      "This interface displays all the basic information about the school's status, including total expenses, total incoming payments, total annual profit, and salaries due for the month. It also shows detailed numbers of students and staff, along with employee attendance times and their monthly due salaries.",
  "تعرض الواجهة انماط الاحداث التي يمكن ان تطبق لكل فئة من المشتركين داخل المنصة بالاضافة الى امكانية عمل نمط حدث جديد":
      "This interface displays event types that can be applied to each category of participants within the platform, along with the ability to create a new event type.",
  "تعرض هذه الواجهة بيانات الامتحانات السابقة مع امكانية اضافة امتحان جديد":
      "This interface displays previous exam data with the ability to add a new exam.",
  "تعرض هذه الواجهة معلومات عن مصاريف هذه السنة مع امكانية اضافة مصروف جديد \n ملاحظة : مصاريف الحافلات تتم اضافتها من واجهة الحافلات":
      "This interface displays information about expenses for the current year with the ability to add a new expense. \n Note: Bus expenses are added from the bus interface.",
  "تقوم هذه الواجهة بعرض معلومات تفصيلية عن الاباء ويمكن من خلالها اضافة اب جديد او تعديل اب موجود سابقا او حذفه":
      "This interface displays detailed information about parents and allows adding a new parent, editing an existing parent, or deleting one.",
  "تستخدم هذه الواجهة لعرض الرواتب المستحقة او المقبوضة لكل موظف حسب شهر معين مع امكانية تسليم رواتب للموظفين":
      "This interface is used to display due or received salaries for each employee by a specific month, with the ability to disburse salaries to employees.",
  "تستخدم هذه الواجهة لعرض تفاصيل المواد داخل المستودع":
      "This interface is used to display details of items in the store.",
  "تعرض هذه الواجهة معلومات عن الطلاب مع امكانية تعديل الطالب او حذفه او اضافة طالب جديد \n ملاحظة١ : عند حذف الطالب يتم حذفه من الاباء ومن الامتحانات التي قام بها ومن الباص المشترك فيه ان كان مشترك \n ملاحظة ٢ : لايمكن تعديل الاب الخاص بالطالب":
      "This interface displays information about students with the ability to edit, delete, or add a new student. \n Note 1: When a student is deleted, they are also removed from parents, exams they took, and the bus they were enrolled in if applicable. \n Note 2: The student's parent cannot be edited.",
  "تعرض هذه الواجهة اجمالي الدفعات المستلمة من الطلاب و اجمالي الدفعات غير المستلمة واجمالي الدفعات المتأخرة عن الدفع عن هذا الشهر مع جدول يوضح تفاصيل الدفعات لكل اب مع امكانية استلام دفعة او التراجع عنها":
      "This interface displays the total received payments from students, total unpaid payments, and total overdue payments for the month, with a table showing payment details for each parent and the ability to receive or reverse a payment.",
  "الصفحة الرئيسية": "Home",
  "الافتراضي": "Default",
"عرض تفاصيل دوام الموظفين": "View Employee Attendance Details",
"تسجيل الدوام": "Record Attendance",
"سجل الدخول باستخدام بطاقتك": "Log in with your card",
"لا يمكن تسجيل دوام اثناء عرض السنة المؤرشفة": "Cannot record attendance during the archived year view",
"اجمالي التأخير": "Total Delay",
"اجمالي الخصم": "Total Deduction",
"الراتب المقطوع": "Net Salary",
"مع مبرر": "With Justification",
"بدون مبرر": "Without Justification",
"يرجى ملء جميع الحقول وتأكد من أن الحقول الرقمية تحتوي على أرقام فقط.": "Please fill in all fields and ensure that numeric fields contain only numbers.",
"خطأ": "Error",
"تم استلام كامل المبلغ": "Full Amount Received",
"الاسم": "Name",
"اسم المادة": "Item Name",
"الكمية": "Quantity",
"رقم الهاتف": "Phone Number",
"رقم هاتف الام": "Mother's Phone Number",
"حفظ": "Save",
"إضافة سجل حدث": "Add Event Record",
"مبلغ التسجيل": "Registration Amount",
"طريقة الدفع": "Payment Method",
"نوع الحدث": "Event Type",
"كاش": "Cash",
"اقساط": "Installments",
"كرديت": "Credit",
"الشهر": "Month",
"الدفعة": "Installment",
"سجل الدفعات": "Payment Record",
"اضافة": "Add",
"الاستاذ": "Teacher",
"العلامة الكامة": "Full Mark",
"اختر الصف": "Select Grade",
"اختر الشعبة للأضافة": "Select Class to Add",
"صورة ورقة الاسئلة": "Question Paper Image",
"صورة ورقة الاجابة": "Answer Sheet Image",
"موجود": "Available",
"اسم الحدث": "Event Name",
"إضافة حدث": "Add Event",
"القيمة": "Value",
"صورة الفاتورة": "Invoice Image",
"التفاصيل": "Details",
"اليوم": "Day",
"الدخول": "Entry",
"الخروج": "Exit",
"المجموع": "Total",
"تأخر بالدخول": "Late Entry",
"التأخير": "Delay",
"عرض المبرر": "Show Justification",
"خروج مبكر": "Early Exit",
"وقت الخروج مبكر": "Early Exit Time",
"الخروج المبكر": "Early Departure",
"تسليم الراتب": "Salary Disbursement",
"الراتب": "Salary",
"اسم المستخدم": "Username",
"كلمة المرور": "Password",
  "مستخدم": "user",
  "مدير": "admin",
"يناير": "Jan",
"فبراير": "Feb",
"مارس": "Mar",
"أبريل": "Apr",
"مايو": "May",
"يونيو": "Jun",
"يوليو": "Jul",
"أغسطس": "Aug",
"سبتمبر": "Sep",
"أكتوبر": "Oct",
"نوفمبر": "Nov",
"ديسمبر": "Dec",
  "اللغة": "Language",
  "عربي": "Arabic",
  "لغات": "Languages",
  "كريدت": "Credit Card",
  "اختر الشعب للأضاف": "Select Sections",
  "نوع الحافلة": "Bus Model",
  'اختر اللغة': "Select Language",
  "ابحث":"Search",
  "صورة العقد":"Contract Image",
  "لا يمكن تعديل الامتحان بعد التصحيح":"The exam cannot be modified after correction",
  'حذف هذا العنصر بشكل نهائي':"Delete this element for ever",
  'هل انت متأكد ؟':"Are you shor?",
  'نعم':"Yes",
  'لا':"No",
  "جاري التحميل":'Loading',
  "يتم العمل على الطلب":'Fetching your data',
  "يناير (1)": "January (1)",
  "فبراير (2)": "February (2)",
  "مارس (3)": "March (3)",
  "أبريل (4)": "April (4)",
  "مايو (5)": "May (5)",
  "يونيو (6)": "June (6)",
  "يوليو (7)": "July (7)",
  "أغسطس (8)": "August (8)",
  "سبتمبر (9)": "September (9)",
  "أكتوبر (10)":"October (10)",
  "نوفمبر (11)": "November (11)",
  "ديسمبر (12)": "December (12)",
  "January (1)": "يناير (1)",
  "February (2)": "فبراير (2)",
  "March (3)": "مارس (3)",
   "April (4)":"أبريل (4)",
  "May (5)": "مايو (5)",
   "June (6)":"يونيو (6)",
   "July (7)":"يوليو (7)",
   "August (8)":"أغسطس (8)",
  "September (9)": "سبتمبر (9)",
  "October (10)":"أكتوبر (10)",
  "November (11)" :"نوفمبر (11)",
  "December (12)": "ديسمبر (12)",
  "الكل":"ALl",
  "ALl":"الكل",
};
