// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLP17C3Be27kztfZAjstWc0lybQKndw8o',
    appId: '1:46598044325:web:a35844b781f3afa31bab4c',
    messagingSenderId: '46598044325',
    projectId: 'vision-educational-de149',
    authDomain: 'vision-educational-de149.firebaseapp.com',
    storageBucket: 'vision-educational-de149.appspot.com',
    measurementId: 'G-1H8Q4VHSBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFlT8CaiD58zsqpZMAKvtekcv9HPXL9nM',
    appId: '1:46598044325:android:e0aae0dff419f4161bab4c',
    messagingSenderId: '46598044325',
    projectId: 'vision-educational-de149',
    storageBucket: 'vision-educational-de149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn_SuHRd7hLA7p0yPIsAZG6sRcnjkUeXo',
    appId: '1:46598044325:ios:082745a47e8c43291bab4c',
    messagingSenderId: '46598044325',
    projectId: 'vision-educational-de149',
    storageBucket: 'vision-educational-de149.appspot.com',
    iosBundleId: 'com.ba3.visionDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn_SuHRd7hLA7p0yPIsAZG6sRcnjkUeXo',
    appId: '1:46598044325:ios:3441c5bd5340e4f81bab4c',
    messagingSenderId: '46598044325',
    projectId: 'vision-educational-de149',
    storageBucket: 'vision-educational-de149.appspot.com',
    iosBundleId: 'com.ba3.visionDashboard.RunnerTests',
  );
}
